Role.create(:id => 3, :title => "3", :desc => "3")
Role.create(:id => 5, :title => "5", :desc => "5")
Role.create(:id => 6, :title => "6", :desc => "6")
Role.create(:id => 7, :title => "7", :desc => "7")
Role.create(:id => 1, :title => "Guest", :desc => "Assigned the first time someone logs in.")
Role.create(:id => 10, :title => "Super Admin", :desc => "Only for programmers of the system")
Role.create(:id => 2, :title => "User", :desc => "This is the normal role")
Role.create(:id => 4, :title => "Organizer", :desc => "The admin for an organization")
Role.create(:id => 9, :title => "SysAdmin", :desc => "Systems Administrators")
Role.create(:id => 8, :title => "Admin", :desc => "Normal Admins")
