Role.create(:id => 3, :title => "3", :desc => "3")
Role.create(:id => 5, :title => "5", :desc => "5")
Role.create(:id => 6, :title => "6", :desc => "6")
Role.create(:id => 7, :title => "7", :desc => "7")
Role.create(:id => 1, :title => "Guest", :desc => "Assigned the first time someone logs in.")
Role.create(:id => 10, :title => "Super Admin", :desc => "Only for programmers of the system")
Role.create(:id => 2, :title => "User", :desc => "This is the normal role")
Role.create(:id => 4, :title => "Organizer", :desc => "The admin for an organization")
Role.create(:id => 9, :title => "SysAdmin", :desc => "Systems Administrators")
Role.create(:id => 8, :title => "Admin", :desc => "Normal Admins")
WoStatus.create(:id => 2, :status => "Processing", :style => "warning")
WoStatus.create(:id => 3, :status => "Working", :style => "info")
WoStatus.create(:id => 4, :status => "Completed", :style => "success")
WoStatus.create(:id => 5, :status => "Error", :style => "error")
WoStatus.create(:id => 1, :status => "New", :style => "new")
Zone.create(:id => 1, :zone => "1")
Zone.create(:id => 2, :zone => "2")
Zone.create(:id => 3, :zone => "3")
Zone.create(:id => 4, :zone => "4")
Zone.create(:id => 5, :zone => "5")
Zone.create(:id => 6, :zone => "6")
Zone.create(:id => 7, :zone => "7")
Zone.create(:id => 8, :zone => "8")
Zone.create(:id => 9, :zone => "9")
Zone.create(:id => 10, :zone => "10")
Zone.create(:id => 11, :zone => "A")